# Generated by Django 5.0.2 on 2024-02-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user_avatar.jpg', upload_to='users/avatar/%Y/%m/%d'),
        ),
    ]
