# Generated by Django 5.0.2 on 2024-02-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookreview_book_bookreview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='book_cover.jpg', upload_to='books/cover/%Y/%m/%d'),
        ),
    ]
