# Generated by Django 5.0.2 on 2024-02-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_published_bookauthor_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookauthor',
            name='email',
            field=models.EmailField(default='user@gmail.com', max_length=254),
        ),
    ]
