# Generated by Django 5.0.2 on 2024-02-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_bookauthor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
